if UnitClassBase("player") ~= "WARLOCK" then return end
local addon, ns = ...

-- 单一职业配置；[1] 仅为像素协议的内部槽位，不代表专精。
Shingen.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = { "锚点", "职业", "专精", "有效性", "移动", "生命值", "队伍人数", "插入法术", "插入物品" },
            ["能量"] = { "法力值" },
            ["目标"] = { "施法技能", "类型", "生命值", "距离" },
            ["焦点"] = { "施法技能", "生命值" },
        },
        auras = {},
        spells = {
            { spellId = 710, name = "放逐术" },
            { spellId = 6229, name = "防护暗影结界" },
            { spellId = 5484, name = "恐惧嚎叫" },
            { spellId = 6789, name = "死亡缠绕" },
            { spellId = 18265, name = "生命虹吸" },
            { spellId = 18708, name = "恶魔支配" },
            { spellId = 19028, name = "灵魂链接" },
            { spellId = 17877, name = "暗影灼烧" },
            { spellId = 17962, name = "燃烧" },
            { spellId = 18223, name = "疲劳诅咒" },
        },
        items = {},
        group = {},
    },
}

Shingen.spellsList = {
    [687] = { index = 1, name = "恶魔皮肤" },
    [348] = { index = 2, name = "献祭" },
    [686] = { index = 3, name = "暗影箭" },
    [688] = { index = 4, name = "召唤小鬼" },
    [172] = { index = 5, name = "腐蚀术" },
    [702] = { index = 6, name = "虚弱诅咒" },
    [1454] = { index = 7, name = "生命分流" },
    [980] = { index = 8, name = "痛苦诅咒" },
    [5782] = { index = 9, name = "恐惧" },
    [6201] = { index = 10, name = "制造治疗石" },
    [1120] = { index = 11, name = "吸取灵魂" },
    [697] = { index = 12, name = "召唤虚空行者" },
    [755] = { index = 13, name = "生命通道" },
    [704] = { index = 14, name = "鲁莽诅咒" },
    [689] = { index = 15, name = "吸取生命" },
    [5697] = { index = 16, name = "魔息术" },
    [693] = { index = 17, name = "制造灵魂石" },
    [5676] = { index = 18, name = "灼热之痛" },
    [706] = { index = 19, name = "魔甲术" },
    [5740] = { index = 20, name = "火焰之雨" },
    [698] = { index = 21, name = "召唤仪式" },
    [712] = { index = 22, name = "召唤魅魔" },
    [126] = { index = 23, name = "基尔罗格之眼" },
    [5138] = { index = 24, name = "吸取法力" },
    [5500] = { index = 25, name = "感知恶魔" },
    [1714] = { index = 26, name = "语言诅咒" },
    [132] = { index = 27, name = "侦测隐形" },
    [710] = { index = 28, name = "放逐术" },
    [6366] = { index = 29, name = "制造火焰石" },
    [1949] = { index = 30, name = "地狱烈焰" },
    [1098] = { index = 31, name = "奴役恶魔" },
    [691] = { index = 32, name = "召唤地狱猎犬" },
    [6229] = { index = 33, name = "防护暗影结界" },
    [2362] = { index = 34, name = "制造法术石" },
    [5484] = { index = 35, name = "恐惧嚎叫" },
    [6789] = { index = 36, name = "死亡缠绕" },
    [6353] = { index = 37, name = "灵魂之火" },
    [1122] = { index = 38, name = "地狱火" },
    [603] = { index = 39, name = "厄运诅咒" },
    [18540] = { index = 40, name = "末日仪式" },
    [18265] = { index = 41, name = "生命虹吸" },
    [18708] = { index = 42, name = "恶魔支配" },
    [19028] = { index = 43, name = "灵魂链接" },
    [17877] = { index = 44, name = "暗影灼烧" },
    [17962] = { index = 45, name = "燃烧" },
    [18223] = { index = 46, name = "疲劳诅咒" },
}
Shingen.itemsList = {}
