if UnitClassBase("player") ~= "WARRIOR" then return end
local addon, ns = ...

-- 单一职业配置；[1] 仅为像素协议的内部槽位，不代表专精。
Shingen.ClassBlocks = {
    [1] = {
        states = {
            ["状态"] = { "锚点", "职业", "专精", "有效性", "移动", "生命值", "队伍人数", "插入法术", "插入物品" },
            ["能量"] = { "怒气值" },
            ["目标"] = { "施法技能", "类型", "生命值", "距离" },
            ["焦点"] = { "施法技能", "生命值" },
        },
        auras = {},
        spells = {
            { spellId = 100, name = "冲锋" },
            { spellId = 355, name = "嘲讽" },
            { spellId = 7384, name = "压制" },
            { spellId = 72, name = "盾击" },
            { spellId = 2565, name = "盾牌格挡" },
            { spellId = 676, name = "缴械" },
            { spellId = 20230, name = "反击风暴" },
            { spellId = 5246, name = "破胆怒吼" },
            { spellId = 1161, name = "挑战怒吼" },
            { spellId = 871, name = "盾墙" },
            { spellId = 20252, name = "拦截" },
            { spellId = 18499, name = "狂暴之怒" },
            { spellId = 6552, name = "拳击" },
            { spellId = 1719, name = "鲁莽" },
            { spellId = 12294, name = "致死打击" },
            { spellId = 23881, name = "嗜血" },
            { spellId = 23922, name = "盾牌猛击" },
            { spellId = 12975, name = "破釜沉舟" },
            { spellId = 12323, name = "刺耳怒吼" },
            { spellId = 12328, name = "死亡之愿" },
            { spellId = 12292, name = "横扫攻击" },
        },
        items = {},
        group = {},
    },
}

Shingen.spellsList = {
    [6673] = { index = 1, name = "战斗怒吼" },
    [2457] = { index = 2, name = "战斗姿态" },
    [78] = { index = 3, name = "英勇打击" },
    [100] = { index = 4, name = "冲锋" },
    [772] = { index = 5, name = "撕裂" },
    [6343] = { index = 6, name = "雷霆一击" },
    [1715] = { index = 7, name = "断筋" },
    [2687] = { index = 8, name = "血性狂暴" },
    [71] = { index = 9, name = "防御姿态" },
    [7386] = { index = 10, name = "破甲攻击" },
    [355] = { index = 11, name = "嘲讽" },
    [7384] = { index = 12, name = "压制" },
    [72] = { index = 13, name = "盾击" },
    [1160] = { index = 14, name = "挫志怒吼" },
    [6572] = { index = 15, name = "复仇" },
    [694] = { index = 16, name = "惩戒痛击" },
    [2565] = { index = 17, name = "盾牌格挡" },
    [676] = { index = 18, name = "缴械" },
    [845] = { index = 19, name = "顺劈斩" },
    [20230] = { index = 20, name = "反击风暴" },
    [1464] = { index = 21, name = "猛击" },
    [5246] = { index = 22, name = "破胆怒吼" },
    [5308] = { index = 23, name = "斩杀" },
    [1161] = { index = 24, name = "挑战怒吼" },
    [871] = { index = 25, name = "盾墙" },
    [2458] = { index = 26, name = "狂暴姿态" },
    [20252] = { index = 27, name = "拦截" },
    [18499] = { index = 28, name = "狂暴之怒" },
    [1680] = { index = 29, name = "旋风斩" },
    [6552] = { index = 30, name = "拳击" },
    [1719] = { index = 31, name = "鲁莽" },
    [12294] = { index = 32, name = "致死打击" },
    [23881] = { index = 33, name = "嗜血" },
    [23922] = { index = 34, name = "盾牌猛击" },
    [12975] = { index = 35, name = "破釜沉舟" },
    [12323] = { index = 36, name = "刺耳怒吼" },
    [12328] = { index = 37, name = "死亡之愿" },
    [12292] = { index = 38, name = "横扫攻击" },
}
Shingen.itemsList = {}
